version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - 3306:3306
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    build: 7/debian-10
    image: suitecrm:8
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_USERNAME=admin
      - SUITECRM_PASSWORD=password
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
      - SUITECRM_SKIP_BOOTSTRAP=true
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
      - '~/provisions/caresherpa/bitnami-docker-suitecrm/7/debian-10/prebuildfs/opt/bitnami/scripts:/opt/bitnami/scripts'
      - '~/provisions/caresherpa/bitnami-docker-suitecrm/7/debian-10/rootfs:/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
